export const SOCKET_EVENTS = {
    CONNECTION: "connection",
    DISCONNECT: "disconnect",
    RECEIVE_MESSAGE: "receive-message",
    MESSAGE_READ: "message-read",
    MESSAGES_READ: "messages-read",
    ONLINE_USERS: "online-users",
    TYPING: "typing",
    GROUP_UPDATED: "group-updated",
    GROUP_DELETED: "group-deleted",
    CONVERSATION_CLEARED: "conversation-cleared",
    CONVERSATION_DELETED: "conversation-deleted",
    JOIN_ROOM: "join-room",
    MARK_AS_READ: "mark-as-read",
    STOP_TYPING: "stop-typing",
    MESSAGE_DELETED: "message-deleted",
    SEND_REACTION: "send-reaction",
    REACTION_UPDATED: "reaction-updated",
    MESSAGE_UPDATED: "message-updated",
    USER_BLOCK_UPDATED: "user-block-updated",
    USER_UPDATED: "user-updated",
    MEMBER_KICKED: "member-kicked",
    MEMBER_LEFT: "member-left",
};
