export const SOCKET_EVENTS = {
    CONNECTION: "connection",
    DISCONNECT: "disconnect",
    RECEIVE_MESSAGE: "receiveMessage",
    MESSAGE_READ: "messageRead",
    MESSAGES_READ: "messagesRead",
    ONLINE_USERS: "onlineUsers",
    TYPING: "typing",
    GROUP_UPDATED: "groupUpdated",
    GROUP_DELETED: "groupDeleted",
    CONVERSATION_CLEARED: "conversationCleared",
    CONVERSATION_DELETED: "conversationDeleted",
    JOIN_ROOM: "joinRoom",
    MARK_AS_READ: "markAsRead",
    STOP_TYPING: "stopTyping",
    MESSAGE_DELETED: "messageDeleted",
    SEND_REACTION: "sendReaction",
    REACTION_UPDATED: "reactionUpdated",
    MESSAGE_UPDATED: "messageUpdated",
};
